import { Skill } from "../middle-end/Loot/Skill";
import { Dungeon } from "../middle-end/Dungeon/Dungeon";
import { Hero } from "../middle-end/Hero/Hero";
import { Encounter} from "../middle-end/Encounter/Encounter";
import { Debuff } from "../middle-end/Debuff/Debuff";

const heroes: { [key: string]: Hero } = {
    "Aquamancer1P": Hero.Aquamancer1P,
    "Aquamancer2P": Hero.Aquamancer2P,
    "Archer1P": Hero.Archer1P,
    "Archer2P": Hero.Archer2P,
    "Dragoon1P": Hero.Dragoon1P,
    "Dragoon2P": Hero.Dragoon2P,
    "Mage1P": Hero.Mage1P,
    "Mage2P": Hero.Mage2P,
    "Paladin1P": Hero.Paladin1P,
    "Paladin2P": Hero.Paladin2P,
    "Rogue1P": Hero.Rogue1P,
    "Rogue2P": Hero.Rogue2P,
    "Warrior1P": Hero.Warrior1P,
    "Warrior2P": Hero.Warrior2P,
    "Witch1P": Hero.Witch1P,
    "Witch2P": Hero.Witch2P
}

const skills: { [key: string]: Skill } = {
    "Tsunami1P": Skill.Tsunami1P,
    "Tsunami2P": Skill.Tsunami2P,
    "BubblesWaterSpirit": Skill.BubblesWaterSpirit,
    "WaterBlessing": Skill.WaterBlessing,
    "EagleEye1P": Skill.EagleEye1P,
    "EagleEye2P": Skill.EagleEye2P,
    "Kiting": Skill.Kiting,
    "CombinedShot": Skill.CombinedShot,
    "Stalwart1P": Skill.Stalwart1P,
    "Stalwart2P": Skill.Stalwart2P,
    "Trident": Skill.Trident,
    "ForkedStrike": Skill.ForkedStrike,
    "ManaCharge1P": Skill.ManaCharge1P,
    "ManaCharge2P": Skill.ManaCharge2P,
    "ShieldAura": Skill.ShieldAura,
    "PowerTransfer": Skill.PowerTransfer,
    "Valiant1P": Skill.Valiant1P,
    "Valiant2P": Skill.Valiant2P,
    "Armor": Skill.Armor,
    "SupportAura": Skill.SupportAura,
    "DaringGamble1P": Skill.DaringGamble1P,
    "DaringGamble2P": Skill.DaringGamble2P,
    "Stealth": Skill.Stealth,
    "Dungeoneering": Skill.Dungeoneering,
    "Frenzy1P": Skill.Frenzy1P,
    "Frenzy2P": Skill.Frenzy2P,
    "SecondWind": Skill.SecondWind,
    "FearlessCharge": Skill.FearlessCharge,
    "HammerSmash1P": Skill.HammerSmash1P,
    "HammerSmash2P": Skill.HammerSmash2P,
    "InnerFire": Skill.InnerFire,
    "AntiHex": Skill.AntiHex,
    "Dodge": Skill.Dodge,
    "Mana": Skill.Mana,
    "Backstab": Skill.Backstab,
    "Cleave": Skill.Cleave,
    "Invisibility": Skill.Invisibility,
    "Accuracy": Skill.Accuracy,
    "CrushingBlow": Skill.CrushingBlow,
    "Valor": Skill.Valor,
    "CriticalStrikes": Skill.CriticalStrikes,
    "Flameweave": Skill.Flameweave,
    "Consistency": Skill.Consistency,
    "ManaFountain": Skill.ManaFountain,
    "Haste": Skill.Haste,
    "CrushingFist": Skill.CrushingFist,
    "Poison": Skill.Poison,
    "ArmorCrush": Skill.ArmorCrush,
    "Heroism": Skill.Heroism,
    "Shimmerblast": Skill.Shimmerblast,
    "LuckyFamiliar": Skill.LuckyFamiliar,
    "Flurry": Skill.Flurry,
    "ChaoticAura": Skill.ChaoticAura,
    "BruteForce": Skill.BruteForce,
    "SteadyHands": Skill.SteadyHands,
    "TripleStrike": Skill.TripleStrike,
    "Dexterity": Skill.Dexterity,
    "Persistence": Skill.Persistence,
    "Clarity": Skill.Clarity,
    "StaticBurst": Skill.StaticBurst,
    "Null": Skill.Null
}

const debuffs: { [key: string]: Debuff } = {
    "Null": Debuff.Null,
    "Dodge": Debuff.Dodge,
    "Survivor": Debuff.Survivor,
    "Flames": Debuff.Flames,
    "Split": Debuff.Split,
    "Swarm": Debuff.Swarm,
    "Frost": Debuff.Frost,
    "Ethereal": Debuff.Ethereal,
    "Fade": Debuff.Fade,
    "Undying": Debuff.Undying,
    "Drain": Debuff.Drain,
    "HallOfStatues": Debuff.HallOfStatues,
    "FlameAura": Debuff.FlameAura,
    "Dragonskin": Debuff.Dragonskin
}
const dungeons: { [key: string]: Dungeon } = {
    "DragonCave": Dungeon.DragonCave,
    "LichTomb": Dungeon.LichTomb,
    "HydraReef": Dungeon.HydraReef,
    "YetiCavern": Dungeon.YetiCavern,
    "MinotaurMaze": Dungeon.MinotaurMaze
};

const encounters: { [key: string]: Encounter } = {
    "ArrowWall1": Encounter.ArrowWall1,
    "ArrowWall2": Encounter.ArrowWall2,
    "Bandit1": Encounter.Bandit1,
    "Bandit2": Encounter.Bandit2,
    "BearTraps1": Encounter.BearTraps1,
    "BearTraps2": Encounter.BearTraps2,
    "Beetle1": Encounter.Beetle1,
    "Beetle2": Encounter.Beetle2,
    "Boulder1": Encounter.Boulder1,
    "Boulder2": Encounter.Boulder2,
    "CaveIn1": Encounter.CaveIn1,
    "CaveIn2": Encounter.CaveIn2,
    "FireElemental1": Encounter.FireElemental1,
    "FireElemental2": Encounter.FireElemental2,
    "FlameStatues1": Encounter.FlameStatues1,
    "FlameStatues2": Encounter.FlameStatues2,
    "ForceWall1": Encounter.ForceWall1,
    "ForceWall2": Encounter.ForceWall2,
    "GloopingOoze1": Encounter.GloopingOoze1,
    "GloopingOoze2": Encounter.GloopingOoze2,
    "Goblin1": Encounter.Goblin1,
    "Goblin2": Encounter.Goblin2,
    "IceElemental1": Encounter.IceElemental1,
    "IceElemental2": Encounter.IceElemental2,
    "LockedDoor1": Encounter.LockedDoor1,
    "LockedDoor2": Encounter.LockedDoor2,
    "Ogre1": Encounter.Ogre1,
    "Ogre2": Encounter.Ogre2,
    "Phantom1": Encounter.Phantom1,
    "Phantom2": Encounter.Phantom2,
    "PitOfSpikes1": Encounter.PitOfSpikes1,
    "PitOfSpikes2": Encounter.PitOfSpikes2,
    "PlagueRat1": Encounter.PlagueRat1,
    "PlagueRat2": Encounter.PlagueRat2,
    "RunePuzzle1": Encounter.RunePuzzle1,
    "RunePuzzle2": Encounter.RunePuzzle2,
    "Shadow1": Encounter.Shadow1,
    "Shadow2": Encounter.Shadow2,
    "Skeleton1": Encounter.Skeleton1,
    "Skeleton2": Encounter.Skeleton2,
    "SpikedLog1": Encounter.SpikedLog1,
    "SpikedLog2": Encounter.SpikedLog2,
    "Wraith1": Encounter.Wraith1,
    "Wraith2": Encounter.Wraith2,
    "Dragon1": Encounter.Dragon1,
    "Lich1": Encounter.Lich1,
    "Hydra1": Encounter.Hydra1,
    "Minotaur1": Encounter.Minotaur1,
    "Yeti1": Encounter.Yeti1
  };

  export {encounters, debuffs, heroes, skills, dungeons};
